services:
  pgadmin:
    ports:
      - 5050:5050
    volumes:
      - ./volumes/pgadmin/:/var/lib/pgadmin/

  db:
    # ports:
    #   - 5432:5432
    volumes:
      - ./volumes/pgdata/:/var/lib/postgresql/data/pgdata/

  backend:
    # ports:
    #   - 8000:8000
    command: [
        "uvicorn",
        "--host=0.0.0.0",
        "--reload",
        # "--workers=4",
        "app.main:app",
        # "--help",
      ]
    volumes:
      - ./src/backend/:/srv/backend/ # src code
