name: ${PROJECT_NAME}-${ENV_NAME} # prefix for the container names, compose-built images, compose volumes, compose networks

services:
  pgadmin:
    image: dpage/pgadmin4:9.8
    environment: # https://www.pgadmin.org/docs/pgadmin4/9.8/container_deployment.html#environment-variables
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL?}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD?}
      - PGADMIN_LISTEN_PORT=5050

  db:
    image: postgres:17.6
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      #
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?}
      - POSTGRES_USER=${POSTGRES_USER?}
      - POSTGRES_DB=${POSTGRES_DB?}

  backend:
    build:
      dockerfile: src/backend/Dockerfile
    tty: true
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - POSTGRES_DSN=postgresql+asyncpg://${POSTGRES_USER?}:${POSTGRES_PASSWORD?}@db/${POSTGRES_DB?}
      #
      - SECRET_KEY=${SECRET_KEY?}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS?}
