services:
  db:
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    image: ${REGISTRY_IMAGE:-${PROJECT_NAME}}/app:${COMMIT_REF_SLUG:-local} # TODO
