services:
  backend:
    ports:
      - 8000:8000
    command: [
        "uvicorn",
        "--host=0.0.0.0",
        "--reload",
        # "--workers=4",
        "app.main:app",
        # "--help",
      ]
    volumes:
      - ./src/backend/:/srv/backend/ # src code

  tunnel:
    image: cloudflare/cloudflared:2025.2.1
    tty: true
    # network_mode: host
    command:
      - tunnel
      - --loglevel=debug
      # - --metrics=0.0.0.0:20241
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARED_TUNNEL_TOKEN}
