volumes: {} # TODO

services:
  pgadmin:
    # ports:
    #   - 5050:5050
    restart: always

  db:
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    # ports:
    #   - 8000:8000
    restart: always
