"""init

Revision ID: 785d82d3818a
Revises:
Create Date: 2025-10-03 06:50:53.600759

"""

from collections.abc import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = '785d82d3818a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
